// Walks public/lenses/ at build time and writes a TypeScript module
// listing every lens id whose product webp exists on disk. LensCard
// imports the generated module to decide between rendering <Image> and
// the Iris fallback for placeholder lenses.
//
// Why a generated module instead of an extra field on the Lens type:
// "does a webp exist in public/lenses/" is a build-output concern, not a
// catalog-data concern. Keeping it out of lenses.json lets the pipeline
// own spec data exclusively and lets x-glass own asset-state detection.

import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { basename, resolve } from "node:path";

const publicLensesDir = resolve(process.cwd(), "public/lenses");
const outputPath = resolve(process.cwd(), "src/data/lens-images.generated.ts");

if (!existsSync(publicLensesDir)) {
  console.warn(`[build-lens-image-manifest] public/lenses missing — writing empty manifest`);
  mkdirSync(resolve(outputPath, ".."), { recursive: true });
  writeFileSync(outputPath, emptyManifest(), "utf8");
  process.exit(0);
}

const ids = readdirSync(publicLensesDir)
  .filter((f) => f.endsWith(".webp"))
  .map((f) => basename(f, ".webp"))
  .sort();

const ts = `// AUTOGENERATED by scripts/build-lens-image-manifest.mts — do not edit.
// Regenerated automatically before \`npm run dev\` and \`npm run build\`.

/**
 * Lens IDs whose product image (\`public/lenses/<id>.webp\`) exists on
 * disk at build time. Generated as scaffold for future card layouts that
 * may need to choose between rendering the processed product image and
 * a fallback when an image is missing — the current catalog schema
 * requires every published lens to ship with an image, so today this
 * just enumerates them all.
 */
export const LENS_IMAGES: ReadonlySet<string> = new Set([
${ids.map((id) => `  ${JSON.stringify(id)},`).join("\n")}
]);
`;

writeFileSync(outputPath, ts, "utf8");
console.log(`✓ wrote lens-images.generated.ts (${ids.length} entries)`);

function emptyManifest(): string {
  return `// AUTOGENERATED by scripts/build-lens-image-manifest.mts — do not edit.
export const LENS_IMAGES: ReadonlySet<string> = new Set([]);
`;
}
